name: Update manifest

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check for updates
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --edit-only flatpak-flutter.yaml

      - name: Check diff
        id: diff
        run: |
          if git diff --quiet; then
            echo update_found=false >> $GITHUB_OUTPUT
          else
            echo update_found=true >> $GITHUB_OUTPUT
          fi

      - name: Remove outdated dependencies
        if: steps.diff.outputs.update_found == 'true'
        run: rm -rf generated

      - name: Get Aria version
        id: get-aria-version
        if: steps.diff.outputs.update_found == 'true'
        run: |
          tag=$(yq .modules[0].sources[0].tag flatpak-flutter.yaml)
          echo version=${tag:1} >> $GITHUB_OUTPUT

      - name: Checkout Aria
        if: steps.diff.outputs.update_found == 'true'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: poppingmoon/aria
          ref: v${{ steps.get-aria-version.outputs.version }}
          path: aria
          persist-credentials: false

      - name: Update Flutter version
        if: steps.diff.outputs.update_found == 'true'
        run: |
          version=$(yq .flutter aria/.fvmrc)
          yq -i .modules[0].sources[1].tag=\"$version\" flatpak-flutter.yaml

      - name: Update Rust version
        if: steps.diff.outputs.update_found == 'true'
        run: |
          version=$(grep channel aria/rust/rust-toolchain.toml | cut -d '"' -f 2)
          yq -i .modules[0].modules[0]=\"generated/modules/rustup-$version.json\" flatpak-flutter.yaml

      - name: Update fvp
        if: steps.diff.outputs.update_found == 'true'
        run: |
          ref=$(yq .dependencies.fvp.git.ref aria/pubspec.yaml)
          if ! grep -q fvp-$ref foreign.json; then
            yq -io json .fvp.manifest.sources[0].dest=\".pub-cache/git/fvp-$ref/linux/mdk-sdk\" foreign.json
            release=$(curl -sL https://api.github.com/repos/wang-bin/mdk-sdk/releases/latest)
            asset=$(echo $release | yq '.assets[] | select(.name == "mdk-sdk-linux.tar.xz")')
            url=$(echo $asset | yq .browser_download_url)
            yq -io json .fvp.manifest.sources[0].url=\"$url\" foreign.json
            digest=$(echo $asset | yq -r .digest)
            yq -io json .fvp.manifest.sources[0].sha256=\"${digest:7}\" foreign.json
          fi

      - name: Update isar
        if: steps.diff.outputs.update_found == 'true'
        run: |
          ref=$(yq .dependency_overrides.isar_community.git.ref aria/pubspec.yaml)
          if ! grep -q isar-community-$ref foreign.json; then
            dest=.pub-cache/git/isar-community-$ref/packages/isar_community
            yq -io json .isar_community.manifest.sources[0].dest=\"$dest/hook\" foreign.json
            yq -io json .isar_community.manifest.sources[1].dest=\"$dest\" foreign.json
            yq -io json .isar_community.manifest.sources[2].dest=\"$dest\" foreign.json

            git clone https://github.com/poppingmoon/isar-community
            pushd isar-community
            git checkout $ref
            popd

            version=$(grep version isar-community/packages/isar_community/lib/src/hook_helpers/version.dart | cut -d "'" -f 2)
            name_x86_64=libisar_x86_64-unknown-linux-gnu.so
            name_aarch64=libisar_aarch64-unknown-linux-gnu.so
            url_x86_64=https://github.com/poppingmoon/isar-community/releases/download/$version/$name_x86_64
            url_aarch64=https://github.com/poppingmoon/isar-community/releases/download/$version/$name_aarch64
            yq -io json .isar_community.manifest.sources[1].url=\"$url_x86_64\" foreign.json
            yq -io json .isar_community.manifest.sources[2].url=\"$url_aarch64\" foreign.json

            hash_x86_64=$(grep -A 1 $name_x86_64 isar-community/packages/isar_community/lib/src/hook_helpers/hashes.dart | tail -n 1 | cut -d "'" -f 2)
            hash_aarch64=$(grep -A 1 $name_aarch64 isar-community/packages/isar_community/lib/src/hook_helpers/hashes.dart | tail -n 1 | cut -d "'" -f 2)
            yq -io json .isar_community.manifest.sources[1].sha256=\"$hash_x86_64\" foreign.json
            yq -io json .isar_community.manifest.sources[2].sha256=\"$hash_aarch64\" foreign.json

            rm -r isar-community
          fi

      - name: Update native_toolchain_cmake
        if: steps.diff.outputs.update_found == 'true'
        run: |
          ref=$(yq .packages.native_toolchain_cmake.description.ref aria/pubspec.lock)
          dest=.pub-cache/git/native_toolchain_cmake-$ref/lib/src/builder
          yq -io json .native_toolchain_cmake.manifest.sources[0].dest=\"$dest\" foreign.json

      - name: Update native_toolchain_rust
        if: steps.diff.outputs.update_found == 'true'
        run: |
          version=$(yq .packages.native_toolchain_rust.version aria/pubspec.lock)
          dest=.pub-cache/hosted/pub.dev/native_toolchain_rust-$version/lib/src
          yq -io json .native_toolchain_rust.manifest.sources[0].dest=\"$dest\" foreign.json

      - name: Remove Aria
        if: steps.diff.outputs.update_found == 'true'
        run: rm -rf aria

      - name: Generate manifest
        if: steps.diff.outputs.update_found == 'true'
        run: >
          docker run --rm -v "$PWD":/usr/src/flatpak -u `id -u`:`id -g`
          theappgineer/flatpak-flutter:latest flatpak-flutter.yaml
          --cargo-locks rust

      - name: Create Pull Request
        if: steps.diff.outputs.update_found == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Update Aria to ${{ steps.get-aria-version.outputs.version }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Update Aria to ${{ steps.get-aria-version.outputs.version }}
